spring.application.name=ssh_ch12_ex3

custom.datasource.url=jdbc:mysql://localhost/spring_start_here?useLegacyDatetimeCode=false&serverTimezone=UTC 

custom.datasource.username=root
custom.datasource.password=
