spring.application.name=ssh_ch12_ex2

spring.datasource.url=jdbc:mysql://localhost/spring_start_here?useLegacyDatetimeCode=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=
spring.sql.init.mode=always
